### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [M4GNV5/Hack.ChatBot#35]
SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at JSON.parse (<anonymous>)
    at Request._callback (/workspaces/Hack.ChatBot/src/commands/joke.js:9:14)
    at self.callback (/workspaces/Hack.ChatBot/node_modules/request/request.js:185:22)
    at Request.emit (node:events:518:28)
    at Request.<anonymous> (/workspaces/Hack.ChatBot/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:518:28)
    at IncomingMessage.<anonymous> (/workspaces/Hack.ChatBot/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:632:28)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.11.0

**Comment by M4GNV5** [comment]
The last commit to this project was 7 years ago. I doubt it will work with node v20.
Furthermore some of the dependencies are outdated and might contain vulnerabilities

But regarding this specific error it looks like the API response from reddit was incorrect. The API used still seems to provide a valid JSON, so maybe this was just a downtime or something in your network was blocking the request.
